export ZSH=$HOME/.oh-my-zsh

export TERM=xterm-256color
[ -n "$TMUX" ] && export TERM=screen-256color

# add ruby gem bin folder in PATH
PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"
# add composer bin folder
PATH="$HOME/.composer/vendor/bin:$PATH"

ZSH_THEME="cool_color"

DEFAULT_USER="count"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

plugins=(git)

source $ZSH/oh-my-zsh.sh
